videojs/videojs-contrib-dash

src/js/videojs-dash.js
Edge browser supports native DASH but has limited support. Place ourselves before the nativeSourceHandler to get first-shot at playing back DASH content
Should fix #14
=> Register before the nativeSourceHandler

src/js/videojs-dash.js
This separates "vjs-dashjs-hide-errors" from previously assigned classes on the element. 
Right now it's impossible to remove the last added class using VideoJS.removeClass because:
1) elmVideo.className = 'foo bar'
2) Html5DashJS.hideErrors() runs
3) elmVideo.className is now 'foo barvjs-dashjs-hide-errors'
4) VideoJS.removeClass('bar') looks for ' bar ', cannot find it and doesn't remove it
=> Add space before vjs-dashjs-hide-errors in className

src/js/videojs-dash.js, test/dashjs.test.js
See: https://groups.google.com/forum/#!topic/dashjs/jQ0B5Q-xOlw
Figured I would create this PR while it is in my mind. There is mention that `Dash.js#1.5.0` will be targeted for `Sep 8, 2015`.
https://github.com/Dash-Industry-Forum/dash.js/blob/69eb95361357cc17613e81f097f8742b09f12cc0/src/streaming/controllers/ProtectionController.js#L241
Anyways, this is minor, but is **BLOCKED** until they release `1.5`.
On the bright side, pointing at the `Dash.js#development`, currently, with `videojs-contrib-dash` seems to be working nicely.
---
Edit: https://twitter.com/DASH_IF/status/641568765998727169
=> Update deprecated `laURL` to utilize new `serverURL`.

src/js/videojs-dash.js, test/dashjs.test.js
A few months ago I added `canPlayType` to the sourcehandlers spec in video.js.
However, this plugin did not use that yet, so I have added it.
I based the code on the HLS plugin, so maybe there are some things that should be done differently, please tell me :).
=> Add canPlayType

package.json
Dash.js 2.0 is using ES6 without producing a browserified dist file which will mess up our tests. This PR specifies dash.js 1.6.0 until dash.js 2.0 is supported (see #38)
=> Set dash.js 1.6.0 as a dependency

Gruntfile.js, package.json
Similar to https://github.com/brightcove/videojs-playlist/pull/44, this allows a user to import contrib-dash without setting video.js and dash.js to window first.
=> Only use browserify-shim when building dist files

README.md
This plugin no longer generates a css file, I'm removing it from the example code.
=> Remove css from README

README.md, example.html, src/js/videojs-dash.js, test/dashjs.test.js
This adds a way to pass options to dash.js using video.js options.
Because the new way (passing `options` to `handleSource`) is new in video.js 5.10, I've made it backwards compatible with video.js 5.9 and lower by still using `tech.options_` if not set. At some point we should probably remove this.
Currently the only option I've added is the "limit bitrate by portal size" option.
Note that the before initialize hook can not be used for these options, as they should be done after initializing.
I also modified / added tests to test for this new feature.
=> Allow to pass option to limit bitrate by portal size

src/js/videojs-dash.js, test/dashjs.test.js, test/integration.test.js
This PR is to place the dashjs mediaplayer on player.dash.mediaPlayer. The media player will be recreated every time a source is loaded in the video.js player.
=> Expose mediaplayer on player

src/js/videojs-dash.js
Can't handle sources with key systems if requestMediaKeySystemAccess/msSetMediaKeys isn't present (Safari for example)
=> Skip src if requestMediaKeySystemAccess isn't present

src/js/videojs-dash.js, test/dashjs.test.js
Dash.js interprets an empty object as disallowing all DRM key systems.
Undefined or null are treated as no options.
Switch to using null so we get the default no options behavior here.
=> Don't pass empty object for key systems.

README.md, src/js/videojs-dash.js, test/dashjs.test.js
Currently,  you have to overwrite `beforeInitialize` for your custom initialization code to run. This can be a problem if multiple plugins want to run initialization code.
This change makes `beforeInitialize` a static api for registering a callback into a list, which will be iterated through and each function called during initialization.
=> Allow for multiple beforeInitialize hooks

README.md, src/js/videojs-dash.js
Allow all configuration options that dash.js supports to be passed at instantiation.
I updated the README.md, but I think my wording is confusing. Can someone please suggest a better way to describe what this does?
~~This will not work on IE8 because of `Object.keys` and `Array.prototype.forEach`. IE8 doesn't support dash anyway, so that shouldn't matter, right?~~
Todo:
Addresses #138
=> Support all dash.js configuration options

README.md, src/js/videojs-dash.js
Allow multiple parameters for dash object configuration and require literal function from dash.js MediaPlayer.
The following will work as expected:
```javascript
videojs(
document.querySelector( ... ), 
{
html5: {
dash: {
setLimitBitrateByPortal: true,
setMaxAllowedBitrateFor: ['video', 2000]
}
}
}
);
```
This deprecates passing a property name like `limitBitrateByPortal` and will log a warning with `videojs.log.warn()`.
---
---
Fixes #143
=> Allow dash config object to accept setters with multiple args

README.md
Added a missing comma per https://github.com/videojs/videojs-contrib-dash/pull/144#issuecomment-277088974
Caused by #144
=> Fix typo dash.js options example in readme

README.md, package.json, src/js/setup-text-tracks.js, src/js/videojs-dash.js
As of video.js v5.14, video.js no longer supports native subtitles on anything besides Safari. For Chrome, this means there is *no* subtitle support. This will wait for dash.js to load all the text tracks and then add them to video.js if we're using a version that does not attempt to use native subtitles. Audio tracks will also be added.
---
](https://github.com/videojs/videojs-contrib-dash/pull/135#issuecomment-277347876)
---
~~Wait for https://github.com/videojs/video.js/pull/4131 to be merged. Add that version as an explicit dependency (maybe change it to a `peerDependency` and `devDependency` since we don't actually need it here?~~
This fix depends on videojs@^v5.18
=> Load text tracks from dash into video.js

.babelrc, package.json, src/js/setup-text-tracks.js, src/js/videojs-dash.js
This change fixes some problems with captions in IE, makes all in-manifest captions of the 'subtitle' type and does not set the default in-manifest track to showing.
=> Fix dashjs text tracks for IE

CHANGELOG.md, src/js/videojs-dash.js, test/dashjs.test.js
Fixes videojs/video.js#4385.
I haven't added tests since stubbing out XHRs in dash.js is probably not very worthwhile with VHS coming along so quickly. But, I can if you really want.
One other thing: I'm not sure if this is the best way of doing it, but when I do class methods in ES6 syntax, I get no `this` inside, and `bind`ing the `this` makes the object hang around (at least in Chrome) on subsequent calls to `src`. I settled with using the `this.fn = () => {}` way of doing things since it got me the `this` and the object didn't hang around in memory.
=> Retrigger dash.js errors on video.js

src/js/videojs-dash.js
When playing a live feed, dash.js sets the duration of the video to be quite large, but not `Number.MAX_VALUE`. Using the `MediaPlayer`'s `isDynamic` is probably a better choice for determining if the feed is live or not.
=> use dynamic status of mpd for infinite duration

src/js/setup-text-tracks.js
If a captions track is present, it will be added as a `subtitles` kind track to video.js. 
You can reproduce this using: https://d2xk91j6i9s5cq.cloudfront.net/test/multi_subtitle_dash/02/presentation-static.mpd. This source has:
- one English captions track
- one English subtitles track
- one Spanish captions track
- one Spanish subtitles track
=> fix: pass the track kind to dashjs

.travis.yml
When I was testing how to get the tests running in the dockerized travis infra, I was running in the travis docker image as root. When moving to the actual travis config, it told me I needed to be root, so without thinking I added `sudo` to the front. I was sure they'd allow package installs, which they do, but only [using the apt addon](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Container-Based-Infrastructure); having `sudo` in the script [would automatically kick you over to the VM-based infra](https://docs.travis-ci.com/user/reference/overview/#For-a-particular-.travis.yml-configuration).
[Until they broke that yesterday.](https://github.com/travis-ci/travis-ci/issues/9875)
Anyway, now we'll actually be using the containerized infra.
=> Fix travis config to actually use container-based infrastructure

CHANGELOG.md, src/js/setup-audio-tracks.js, src/js/setup-text-tracks.js
The current way the event handlers are registered / unregistered for text and audio track changes causes problems when switching between `SourceHandler`s. This change seems to prevent it, at least from my testing with contrib-dash and contrib-hls.
There should probably be some automated tests here checking to make sure that's actually the case.
=> cleanup event handler addition/removal to not bork on source change

CHANGELOG.md, src/js/videojs-dash.js, test/dashjs.test.js
See #307 for the back-and-forth. I'm not sure why, but for whatever reason us setting the text track index to -1 and calling `setTextDefaultEnabled(false)`, which sets the text track index to -1, do not result in the same behaviour. It must be a timing thing.
Call `setTextDefaultEnabled(false)` before `initialize()` on the dash.js `mediaPlayer` instance.
=> fix bug in vtt captions not showing (closes #307)

package-lock.json, package.json
When we added rollup plugins to bundle dash.js we added them as dependencies and not devDependencies.
=> fix: rollup plugins should be dev dependencies

.github/workflows/ci.yml
* Update deprecated set-output command. This will stop working in June 2023. See [this post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
* Update actions to use Node 16 rather than Node 12. Github are currently migrating away from Node 12. See [this post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
GabrielBB/xvfb-action is no longer maintained and there is no Node 16 version. Therefore it was replaced with coactions/setup-xvfb.
=> chore: Update CI workflow
