package.json
Addresses https://github.com/videojs/videojs-contrib-dash/issues/17
=> Update package.json to include `main` attribute for UMD support.

Gruntfile.js, README.md, example.html, package.json, src/js/videojs-dash.js, test/dashjs.test.js, test/globals.test.js, test/index.html, test/integration.html, test/integration.test.js, test/karma.config.js
This PR is to update the plugin to support dash.js 2.0
Todo:
=> Update contrib-dash for dash.js 2.0

Gruntfile.js, example.html, package.json, src/.jshintrc, src/js/videojs-dash.js, test/index.html, test/integration.html
This PR is to build the plugin using browserify.
=> Browserify videojs-contrib-dash

.travis.yml, Gruntfile.js, test/integration.test.js, test/karma.config.js
Use a different sample video for integration tests
=> Only use Firefox on Pull Requests

src/js/videojs-dash.js
Don't create MediaPlayer if it already exists and don't manually reset (this is messing up changing sources).
=> Fix changing source issues

.gitignore, Gruntfile.js, package.json, src/.jshintrc, src/js/videojs-dash.js
This PR is to rewrite this plugin using ES6 with babel.
This closes #38 and #59
=> ES6 rewrite

index.html
=> Use https source

Gruntfile.js, README.md, index.html, package.json
Move babelified file
Remove babelify from the build process
=> Clean up the build process

Gruntfile.js, package.json, test/browserify.test.js, test/index.html, test/integration.test.js, test/karma.config.js, test/webpack.test.js
Requires a new version of dash.js to work properly.
=> Added browerify/webpack tests

src/js/videojs-dash.js
=> override duration method to change Number.MAX_VALUE to Infinity for live streams

src/js/videojs-dash.js, test/dashjs.test.js
=> fix: Call update source hook when checking to see if a source can be handled

package.json
=> enable linting on test files

.jshintrc, src/.jshintrc, test/.jshintrc, test/dashjs.test.js
missed a couple lint changes in #224
=> lint fixes

src/js/videojs-dash.js, test/dashjs.test.js
=> add error handler for new mssError error in dash v2.6.8

src/js/videojs-dash.js
After speaking with some people in the dash-if slack, it sounds like the best method for determining if a feed is live is by checking both the `isDynamic` and checking the manifest to see if it has a duration.
=> further improvements to duration / checking live

package-lock.json, package.json
Security updates and update the karma tool
=> ignore: update npm-run-all to 4.1.5

CHANGELOG.md, README.md, package-lock.json, package.json, src/js/setup-audio-tracks.js, src/js/setup-text-tracks.js
Use the track label once that is available.  It will be available if/when this gets merged in: https://github.com/Dash-Industry-Forum/dash.js/pull/2929 and released.
The `Label` is useful for adding human readable values in the audio/captions menus instead of language codes.
Please list the specific changes involved in this pull request.
=> feat(text-tracks): Use track label instead of lang

package-lock.json, package.json, test/build.test.js, test/integration.test.js
This updates [dash.js](https://github.com/Dash-Industry-Forum/dash.js) from 2.9.3 to 3.1.3
=> chore(package): Update Dash.js to v3.1.3

package-lock.json, package.json, scripts/rollup.config.js
=> feat: include dash.js in build

README.md
Update Dash version in README to match what's used in package.json
Closes #336
=> Update README to show support for Dash 3.x
